### PR TITLE
ZENKO-2761 delete location

### PR DESCRIPTION
**Pull request by nicolas2bert**
Screen-Recording-2020-08-27-at-6 44 10-PM

### CODE REVIEW

**Comment by rachedbenmustapha** [comment]
It looks like the location is hierarchically under the account on the left, how is this achieved?

**Comment by nicolas2bert** [comment]
@RachedBenMustapha for now, all accounts should be able to see/use all the locations. 
So although this layout's design implies that there is a hierarchy, there is no for now.

Later this "locations tab" will let the storage manager attach location(s) to a specific account.
@terrydervaux please correct me if I am wrong.

**Review by terrydervaux — APPROVED** [review]
Looks good to me, and I'm ok with the behavior you are describing.

**Review by tmacro — APPROVED** [review]

**Comment by nicolas2bert** [comment]
@bert-e approve

**Pull request merged**
