### PR TITLE
ZKUI-140: support metadata search with list versions

### PR DESCRIPTION
**Pull request by ChengYanJin**
support metadata search with list versions is on

### CODE REVIEW

**Review by JBWatenbergScality — COMMENTED** [review]
First review submitted on https://github.com/scality/zenko-ui/pull/329

**Review by JBWatenbergScality — APPROVED** [review]
LGTM, Could you please open a ticket to track the lack of test for search metadata and pagination on the data browser ?

**Comment by ChengYanJin** [comment]
Yes.  Good point!
We will handle the pagination on this ticket https://scality.atlassian.net/browse/ARTESCA-4291

**Pull request merged**
