### PR TITLE
ZENKO-3004 Object versioning - first iteration

### PR DESCRIPTION
**Pull request by nicolas2bert**

### CODE REVIEW

**Review by romainlancia — APPROVED** [review]
LGTM

**Review by Cuervino — APPROVED** [review]
1 hour of gap between the "Modified on" on the table and the one from the Summary
2020-12-11_17h31_48

Few bugs when loading the buckets for the first time (works the second time)
2020-12-11_17h32_43

otherwise, LGTM

**Comment by terrydervaux** [comment]
Downloading an object in a versioned bucket is broken. Do you want to address that is this PR?

Show version on:
Screenshot 2020-12-11 at 10 18 05

Show version off:
Screenshot 2020-12-11 at 10 18 45

**Review by terrydervaux — CHANGES_REQUESTED** [review]
The current display of disabled buttons is very confusing me. Do you think you can fix that?

Screenshot 2020-12-11 at 10 27 13

**Review by terrydervaux — CHANGES_REQUESTED** [review]
With the current implementation, objects metadata and tags can be saved even if there is no update in the metadata or tag. The expect behavior is: Only when a metadata or a tag has been added, the save button is enabled. 

For metadata tab, it leads to 3 issues: 
- Zenko-ui creates a new object version 
- Zenko-ui updates the metadata content-type by adding charset=UTF-8
- Show version page is totally broken 

## Step to reproduce
- Upload an object in a versioned bucket, and check metadata
Screenshot 2020-12-11 at 10 56 07 (2)
- Click on the save button in the metadata tab and observe the metadata
Screenshot 2020-12-11 at 10 57 49 (2)
- Save one more time and turn on the list version toogle
Screenshot 2020-12-11 at 11 00 38 (2)

**Comment by terrydervaux** [comment]
> The current display of disabled buttons is very confusing me. Do you think you can fix that?
> 
> Screenshot 2020-12-11 at 10 27 13

Following our discussion on slack, this issue is not related to bucket versioning. I created https://scality.atlassian.net/browse/ZENKO-3046

**Comment by terrydervaux** [comment]
> With the current implementation, objects metadata and tags can be saved even if there is no update in the metadata or tag. The expect behavior is: Only when a metadata or a tag has been added, the save button is enabled.
> 
> For metadata tab, it leads to 3 issues:
> 
> * Zenko-ui creates a new object version
> * Zenko-ui updates the metadata content-type by adding charset=UTF-8
> * Show version page is totally broken
> 
> ## Step to reproduce
> * Upload an object in a versioned bucket, and check metadata
>   Screenshot 2020-12-11 at 10 56 07 (2)
> * Click on the save button in the metadata tab and observe the metadata
>   Screenshot 2020-12-11 at 10 57 49 (2)
> * Save one more time and turn on the list version toogle
>   Screenshot 2020-12-11 at 11 00 38 (2)

For the same reason as my previous comment, I created this https://scality.atlassian.net/browse/ZENKO-3047

**Review by terrydervaux — APPROVED** [review]

**Comment by nicolas2bert** [comment]
@bert-e approve

**Pull request merged**
