### PR TITLE
ZENKO-2858 Object Tags: first iteration

### PR DESCRIPTION
**Pull request by nicolas2bert**
Screen-Recording-2020-10-22-at-3 05 51-PM

### CODE REVIEW

**Comment by miniscruff** [comment]
It might just be me but I think the colon between the two fields looks a little strange. Also I kinda think the [+] button should be on the next line as it doesn't actually effect the line it is on.

**Comment by nicolas2bert** [comment]
Ok I will get rid of the colon since you are not the first one asking for it. About the add/subtract buttons logic, it has been implemented for metadata as well. I will add your comment for our next iteration. https://scality.atlassian.net/browse/ZENKO-2877

Screen Shot 2020-10-22 at 4 46 26 PM

**Review by miniscruff — APPROVED** [review]

**Review by romainlancia — APPROVED** [review]
LGTM

**Comment by nicolas2bert** [comment]
@bert-e approve

**Pull request merged**
