### PR TITLE
Fix lato font (doesn't apply for all html elements)

### PR DESCRIPTION
**Pull request by theocerutti**
Lato font doesn't apply on every html elements

### CODE REVIEW

**Review by Cuervino — APPROVED** [review]
Fixed the issue on my ptf.

**Comment by nicolas2bert** [comment]
Is there a ticket for this one? Does not know where to look at?

**Comment by nicolas2bert** [comment]
Does not know where to look at?

**Comment by Cuervino** [comment]
I "forgot" to create the ticket, here it is
https://scality.atlassian.net/browse/ZENKO-3417

**Review by nicolas2bert — APPROVED** [review]

**Comment by theocerutti** [comment]
@bert-e approve

**Pull request merged**
