### PR TITLE
Improvement/zk UI 77 add xdm toggle feature

### PR DESCRIPTION
**Pull request by JBWatenbergScality**
@Cuervino shall I rename Async Notification to Async Metadata updates here ?

### CODE REVIEW

**Comment by Cuervino** [comment]
> 

Yes, if possible, you can do it please.

**Review by ChengYanJin — APPROVED** [review]
LGTM!

**Comment by JBWatenbergScality** [comment]
> > 
> 
> Yes, if possible, you can do it please.

I will do it in another PR as we are still unsure that we want to merge it, I need a confirmation from Thomas as soon as I get enough approvals.

**Review by MonPote — APPROVED** [review]
LGTM (the code)

**Pull request merged**
