### PR TITLE
ZENKO-3180: Update version of core-ui to v0.14.1

### PR DESCRIPTION
**Pull request by theocerutti**
Update core-ui version from v0.10.0 to v0.14.1.

### CODE REVIEW

**Review by Cuervino — APPROVED** [review]
Loading/working.

**Comment by nicolas2bert** [comment]
Screen Shot 2021-04-02 at 5 17 43 PM
Did you notice the "plus" button is acting weird @Cuervino ? 
It can be fixed later.
@theocerutti can you `git rebase development/1.0`, I will approve it. :) Thank you.

**Review by nicolas2bert — APPROVED** [review]

**Comment by nicolas2bert** [comment]
@bert-e approve

**Comment by nicolas2bert** [comment]
@theocerutti you can do a @bert-e approve once you get 2 approvals.

**Comment by theocerutti** [comment]
@bert-e approve

**Comment by theocerutti** [comment]
@bert-e approve

**Comment by Cuervino** [comment]
> 
> 
> Screen Shot 2021-04-02 at 5 17 43 PM
> Did you notice the "plus" button is acting weird @Cuervino ? It can be fixed later. @theocerutti can you `git rebase development/1.0`, I will approve it. :) Thank you.

In fact, I did not see any issue with these "plus" button alignment from my side.

**Pull request merged**
