### PR TITLE
fix:ZENKO-3179  add copy icon to missing fields

### PR DESCRIPTION
**Pull request by romainlancia**
Screenshot from 2021-04-15 16-48-01

### CODE REVIEW

**Comment by Cuervino** [comment]
- "Creation date" and "Quota" don't require a copy icon;
-  the icon is: clone | `<i class="far fa-clone"></i>` | regular Style (far);
- the font color for this icon is b5b5b5.

**Review by Cuervino — CHANGES_REQUESTED** [review]
1. From the screenshot provided in the PR, here is the target design:
- "Creation date" and "Quota" don't require a copy icon;
- the icon is: clone | <i class="far fa-clone"></i> | regular Style (far);
- the font color for this icon is b5b5b5.

2. I launched the branch, but I cannot see any icon added on the GUI?
image
Is it linked with another PR? which one?

@lebroz

**Comment by Cuervino** [comment]
@alexis-ld @lebroz 
Could you please give me a status on this PR? 
When I cherry-pick the commit, I don't see any icons on the UI.

**Comment by romainlancia** [comment]
@Cuervino Hello, sorry for the late message... I missed the email notification about your message at some point and I'm sorry about that.
Regarding, the issue, from which branch did you took the screenshot actually ? Because, I have some doubts now like is this issue was already fix ? Because I started my work from developement1.0 and without my changes I have this:

Screenshot from 2021-04-15 16-48-32

I thought you wanted to add icons next to "Creation date" and "Quota" but apparently it is not the case.

**Comment by Cuervino** [comment]
@nicolas2bert Could you please check and review this PR? 
As I don't see the icons, maybe it's coming from my GitHub (windows issue?)

**Review by Cuervino — APPROVED** [review]

**Comment by nicolas2bert** [comment]
Are you able to see the "clone" icons now @Cuervino ? If not, it needs to be investigated because I was able to see icons before this commit.

**Review by terrydervaux — APPROVED** [review]
LGTM, @lebroz can you merge the PR please.

**Pull request merged**
