### PR TITLE
select account on create workflow

### PR DESCRIPTION
**Pull request by AsmaaELM**
Issue:  https://scality.atlassian.net/browse/ZKUI-125

### CODE REVIEW

**Comment by AsmaaELM** [comment]
ping

**Review by ChengYanJin — APPROVED** [review]
LGTM!
Not related to your PR, but I found an issue with the account selector, when I scroll down it's getting blurring.. we should investigate this issue.

**Comment by ChengYanJin** [comment]
there is little shifting because the account selector in /workflow and in /create-workflow, it might be a quick fix ;)

**Comment by AsmaaELM** [comment]
> there is little shifting because the account selector in /workflow and in /create-workflow, it might be a quick fix ;)

Yeah, thanks for the info. I fix it by increasing the width in the Breadcrumb.tsx

**Comment by AsmaaELM** [comment]
ping

**Comment by AsmaaELM** [comment]
ping

**Pull request merged**
