### PR TITLE
ZKUI-228: Added a clarification message about the consequences of deleting objects and versions

### PR DESCRIPTION
**Pull request by ognyan-kostadinov**

### CODE REVIEW

**Comment by ognyan-kostadinov** [comment]
multiple-objects
multiple-versions
one-object
one-version

**Comment by Cuervino** [comment]
2 comments: 
- could you add "dot" at the end of the notification sentence (for instance: 
`The selected versions will be permanently removed from the Bucket.` 
)
- The font in the notification seems to be bold, where it would be better to have a TextBasic style. Maybe it's related to the Core-ui component?
image

**Comment by Cuervino** [comment]
Additional question: did you check the new behaviour against "Object-locked" deletion modal ?

**Review by ChengYanJin — CHANGES_REQUESTED** [review]
Hello @ognyan-kostadinov, 
Before checking the code, there are a few cases we should double-check with @Cuervino about the behavior. 

1. the delete marker only applies to the buckets which are **versioning**.  If the buckets are not versioning enabled, when we delete an object, it will be permanently deleted.
2. for the object with **legal hold** enabled, I think it's better to NOT display such notification (+ confirm checkbox). 
3. In the modal, if we remove all the objects, the banner should disappear as well.

**Review by ChengYanJin — APPROVED** [review]
Let's get it merged!
For the suspended versioning bucket, we will check it later and create a ticket if it's needed.

**Pull request merged**
