### PR TITLE
ZENKO-3627: making the tooltips fit better the contents they display

### PR DESCRIPTION
**Pull request by JulienMeziere**
To make the size of the tooltips consistent no matter the size of the screen, I've chosen to use rem to define the width of the tooltips.

Jira ticket: https://scality.atlassian.net/browse/ZENKO-3627

### CODE REVIEW

**Comment by elenamarcova** [comment]
@naren-rajendran could you please review this PR ?

**Review by nicolas2bert — APPROVED** [review]
Code looks good to me, @Cuervino would you mind doing a UX check please.

**Review by Cuervino — CHANGES_REQUESTED** [review]
I would like us to investigate in order to find a solution doesn't rely on custom rem values.

**Review by Cuervino — APPROVED** [review]
Good for me!

**Review by naren-rajendran — APPROVED** [review]

**Pull request merged**
