### PR TITLE
Solve s3 proxy issues for object with keys containing urlencoded chars

### PR DESCRIPTION
**Pull request by JBWatenbergScality**

### CODE REVIEW

**Comment by MonPote** [comment]
test

**Comment by ChengYanJin** [comment]
THIS IS AMAZING !

**Review by ChengYanJin — APPROVED** [review]

**Review by MonPote — APPROVED** [review]

**Comment by JBWatenbergScality** [comment]
Absorbed and superseded by https://github.com/scality/zenko-ui/pull/619

**Pull request closed without merging**
